### PR TITLE
Updated README.md concerning missing packages (ex: distutils)

### PR DESCRIPTION
**Pull request by Ragnarok700**
Added a mention under prerequisites of how to deal with missing packages such as distutils, which is no longer part of the Python distribution and thus not available by default/without manual steps currently.

### CODE REVIEW

**Comment by Ragnarok700** [comment]
This was simple enough to fix with a quick online search and bare bone know-how, but I figure it is best to have it explained explicitly vs letting people try and figure it out and possible open issues about it.

**Comment by miku448** [comment]
we don't have any python scripts or dependencies in this repository. why would this be needed?

**Comment by miku448** [comment]
closing it for now as I don't see the need for it

**Comment by miku448** [comment]
Apologies, this looks like something actually required by python `3.12+`

**Comment by miku448** [comment]
Thank you so much!

**Pull request merged**
